## ML model for mushroom classification 

In [6]:
import torch

In [25]:
a = torch.tensor([1,2,3])
b = torch.rand(3)

In [27]:
print(a)
print(b)

tensor([1, 2, 3])
tensor([0.0143, 0.6012, 0.1434])


In [28]:
print(torch.multiply(a,b))

tensor([0.0143, 1.2024, 0.4301])
